export {
  canAccessAssignedDelivery,
  canManageCatalog,
  canManageCoupons,
  canManageCustomers,
  canManageDelivery,
  canManageFinance,
  canManageOrders,
  canPerform,
  canViewDashboard,
  canViewOrders,
  canWriteData,
  hasPermission,
  hasRoutePermission,
} from "@/lib/admin/permissions";
